import React from "react";
import {ReactComponent as AC} from "./svg/ac.svg";
import {ReactComponent as AD} from "./svg/ad.svg";
import {ReactComponent as AE} from "./svg/ae.svg";
import {ReactComponent as AF} from "./svg/af.svg";
import {ReactComponent as AG} from "./svg/ag.svg";
import {ReactComponent as AI} from "./svg/ai.svg";
import {ReactComponent as AL} from "./svg/al.svg";
import {ReactComponent as AM} from "./svg/am.svg";
import {ReactComponent as AO} from "./svg/ao.svg";
import {ReactComponent as AQ} from "./svg/aq.svg";
import {ReactComponent as AR} from "./svg/ar.svg";
import {ReactComponent as AS} from "./svg/as.svg";
import {ReactComponent as AT} from "./svg/at.svg";
import {ReactComponent as AU} from "./svg/au.svg";
import {ReactComponent as AW} from "./svg/aw.svg";
import {ReactComponent as AX} from "./svg/ax.svg";
import {ReactComponent as AZ} from "./svg/az.svg";
import {ReactComponent as BA} from "./svg/ba.svg";
import {ReactComponent as BB} from "./svg/bb.svg";
import {ReactComponent as BD} from "./svg/bd.svg";
import {ReactComponent as BE} from "./svg/be.svg";
import {ReactComponent as BF} from "./svg/bf.svg";
import {ReactComponent as BG} from "./svg/bg.svg";
import {ReactComponent as BH} from "./svg/bh.svg";
import {ReactComponent as BI} from "./svg/bi.svg";
import {ReactComponent as BJ} from "./svg/bj.svg";
import {ReactComponent as BL} from "./svg/bl.svg";
import {ReactComponent as BM} from "./svg/bm.svg";
import {ReactComponent as BN} from "./svg/bn.svg";
import {ReactComponent as BO} from "./svg/bo.svg";
import {ReactComponent as BQ} from "./svg/bq.svg";
import {ReactComponent as BR} from "./svg/br.svg";
import {ReactComponent as BS} from "./svg/bs.svg";
import {ReactComponent as BT} from "./svg/bt.svg";
import {ReactComponent as BV} from "./svg/bv.svg";
import {ReactComponent as BW} from "./svg/bw.svg";
import {ReactComponent as BY} from "./svg/by.svg";
import {ReactComponent as BZ} from "./svg/bz.svg";
import {ReactComponent as CA} from "./svg/ca.svg";
import {ReactComponent as CC} from "./svg/cc.svg";
import {ReactComponent as CD} from "./svg/cd.svg";
import {ReactComponent as CF} from "./svg/cf.svg";
import {ReactComponent as CG} from "./svg/cg.svg";
import {ReactComponent as CH} from "./svg/ch.svg";
import {ReactComponent as CI} from "./svg/ci.svg";
import {ReactComponent as CK} from "./svg/ck.svg";
import {ReactComponent as CL} from "./svg/cl.svg";
import {ReactComponent as CM} from "./svg/cm.svg";
import {ReactComponent as CN} from "./svg/cn.svg";
import {ReactComponent as CO} from "./svg/co.svg";
import {ReactComponent as CP} from "./svg/cp.svg";
import {ReactComponent as CR} from "./svg/cr.svg";
import {ReactComponent as CU} from "./svg/cu.svg";
import {ReactComponent as CV} from "./svg/cv.svg";
import {ReactComponent as CW} from "./svg/cw.svg";
import {ReactComponent as CX} from "./svg/cx.svg";
import {ReactComponent as CY} from "./svg/cy.svg";
import {ReactComponent as CZ} from "./svg/cz.svg";
import {ReactComponent as DE} from "./svg/de.svg";
import {ReactComponent as DG} from "./svg/dg.svg";
import {ReactComponent as DJ} from "./svg/dj.svg";
import {ReactComponent as DK} from "./svg/dk.svg";
import {ReactComponent as DM} from "./svg/dm.svg";
import {ReactComponent as DO} from "./svg/do.svg";
import {ReactComponent as DZ} from "./svg/dz.svg";
import {ReactComponent as EA} from "./svg/ea.svg";
import {ReactComponent as EC} from "./svg/ec.svg";
import {ReactComponent as EE} from "./svg/ee.svg";
import {ReactComponent as EG} from "./svg/eg.svg";
import {ReactComponent as EH} from "./svg/eh.svg";
import {ReactComponent as EN} from "./svg/en.svg";
import {ReactComponent as ER} from "./svg/er.svg";
import {ReactComponent as ES_CT} from "./svg/es-ct.svg";
import {ReactComponent as ES_GA} from "./svg/es-ga.svg";
import {ReactComponent as ES} from "./svg/es.svg";
import {ReactComponent as ET} from "./svg/et.svg";
import {ReactComponent as EU} from "./svg/eu.svg";
import {ReactComponent as FI} from "./svg/fi.svg";
import {ReactComponent as FJ} from "./svg/fj.svg";
import {ReactComponent as FK} from "./svg/fk.svg";
import {ReactComponent as FM} from "./svg/fm.svg";
import {ReactComponent as FO} from "./svg/fo.svg";
import {ReactComponent as FR} from "./svg/fr.svg";
import {ReactComponent as GA} from "./svg/ga.svg";
import {ReactComponent as GB} from "./svg/gb.svg";
import {ReactComponent as GD} from "./svg/gd.svg";
import {ReactComponent as GE} from "./svg/ge.svg";
import {ReactComponent as GF} from "./svg/gf.svg";
import {ReactComponent as GG} from "./svg/gg.svg";
import {ReactComponent as GH} from "./svg/gh.svg";
import {ReactComponent as GI} from "./svg/gi.svg";
import {ReactComponent as GL} from "./svg/gl.svg";
import {ReactComponent as GM} from "./svg/gm.svg";
import {ReactComponent as GN} from "./svg/gn.svg";
import {ReactComponent as GP} from "./svg/gp.svg";
import {ReactComponent as GQ} from "./svg/gq.svg";
import {ReactComponent as GR} from "./svg/gr.svg";
import {ReactComponent as GS} from "./svg/gs.svg";
import {ReactComponent as GT} from "./svg/gt.svg";
import {ReactComponent as GU} from "./svg/gu.svg";
import {ReactComponent as GW} from "./svg/gw.svg";
import {ReactComponent as GY} from "./svg/gy.svg";
import {ReactComponent as HK} from "./svg/hk.svg";
import {ReactComponent as HM} from "./svg/hm.svg";
import {ReactComponent as HN} from "./svg/hn.svg";
import {ReactComponent as HR} from "./svg/hr.svg";
import {ReactComponent as HT} from "./svg/ht.svg";
import {ReactComponent as HU} from "./svg/hu.svg";
import {ReactComponent as IC} from "./svg/ic.svg";
import {ReactComponent as ID} from "./svg/id.svg";
import {ReactComponent as IE} from "./svg/ie.svg";
import {ReactComponent as IL} from "./svg/il.svg";
import {ReactComponent as IM} from "./svg/im.svg";
import {ReactComponent as IN} from "./svg/in.svg";
import {ReactComponent as IO} from "./svg/io.svg";
import {ReactComponent as IQ} from "./svg/iq.svg";
import {ReactComponent as IR} from "./svg/ir.svg";
import {ReactComponent as IS} from "./svg/is.svg";
import {ReactComponent as IT} from "./svg/it.svg";
import {ReactComponent as JE} from "./svg/je.svg";
import {ReactComponent as JM} from "./svg/jm.svg";
import {ReactComponent as JO} from "./svg/jo.svg";
import {ReactComponent as JP} from "./svg/jp.svg";
import {ReactComponent as KE} from "./svg/ke.svg";
import {ReactComponent as KG} from "./svg/kg.svg";
import {ReactComponent as KH} from "./svg/kh.svg";
import {ReactComponent as KI} from "./svg/ki.svg";
import {ReactComponent as KM} from "./svg/km.svg";
import {ReactComponent as KN} from "./svg/kn.svg";
import {ReactComponent as KP} from "./svg/kp.svg";
import {ReactComponent as KR} from "./svg/kr.svg";
import {ReactComponent as KW} from "./svg/kw.svg";
import {ReactComponent as KY} from "./svg/ky.svg";
import {ReactComponent as KZ} from "./svg/kz.svg";
import {ReactComponent as LA} from "./svg/la.svg";
import {ReactComponent as LB} from "./svg/lb.svg";
import {ReactComponent as LC} from "./svg/lc.svg";
import {ReactComponent as LI} from "./svg/li.svg";
import {ReactComponent as LK} from "./svg/lk.svg";
import {ReactComponent as LR} from "./svg/lr.svg";
import {ReactComponent as LS} from "./svg/ls.svg";
import {ReactComponent as LT} from "./svg/lt.svg";
import {ReactComponent as LU} from "./svg/lu.svg";
import {ReactComponent as LV} from "./svg/lv.svg";
import {ReactComponent as LY} from "./svg/ly.svg";
import {ReactComponent as MA} from "./svg/ma.svg";
import {ReactComponent as MC} from "./svg/mc.svg";
import {ReactComponent as MD} from "./svg/md.svg";
import {ReactComponent as ME} from "./svg/me.svg";
import {ReactComponent as MF} from "./svg/mf.svg";
import {ReactComponent as MG} from "./svg/mg.svg";
import {ReactComponent as MH} from "./svg/mh.svg";
import {ReactComponent as MK} from "./svg/mk.svg";
import {ReactComponent as ML} from "./svg/ml.svg";
import {ReactComponent as MM} from "./svg/mm.svg";
import {ReactComponent as MN} from "./svg/mn.svg";
import {ReactComponent as MO} from "./svg/mo.svg";
import {ReactComponent as MP} from "./svg/mp.svg";
import {ReactComponent as MQ} from "./svg/mq.svg";
import {ReactComponent as MR} from "./svg/mr.svg";
import {ReactComponent as MS} from "./svg/ms.svg";
import {ReactComponent as MT} from "./svg/mt.svg";
import {ReactComponent as MU} from "./svg/mu.svg";
import {ReactComponent as MV} from "./svg/mv.svg";
import {ReactComponent as MW} from "./svg/mw.svg";
import {ReactComponent as MX} from "./svg/mx.svg";
import {ReactComponent as MY} from "./svg/my.svg";
import {ReactComponent as MZ} from "./svg/mz.svg";
import {ReactComponent as NA} from "./svg/na.svg";
import {ReactComponent as NC} from "./svg/nc.svg";
import {ReactComponent as NE} from "./svg/ne.svg";
import {ReactComponent as NF} from "./svg/nf.svg";
import {ReactComponent as NG} from "./svg/ng.svg";
import {ReactComponent as NI} from "./svg/ni.svg";
import {ReactComponent as NL} from "./svg/nl.svg";
import {ReactComponent as NO} from "./svg/no.svg";
import {ReactComponent as NP} from "./svg/np.svg";
import {ReactComponent as NR} from "./svg/nr.svg";
import {ReactComponent as NU} from "./svg/nu.svg";
import {ReactComponent as NZ} from "./svg/nz.svg";
import {ReactComponent as OM} from "./svg/om.svg";
import {ReactComponent as PA} from "./svg/pa.svg";
import {ReactComponent as PE} from "./svg/pe.svg";
import {ReactComponent as PF} from "./svg/pf.svg";
import {ReactComponent as PG} from "./svg/pg.svg";
import {ReactComponent as PH} from "./svg/ph.svg";
import {ReactComponent as PK} from "./svg/pk.svg";
import {ReactComponent as PL} from "./svg/pl.svg";
import {ReactComponent as PM} from "./svg/pm.svg";
import {ReactComponent as PN} from "./svg/pn.svg";
import {ReactComponent as PR} from "./svg/pr.svg";
import {ReactComponent as PS} from "./svg/ps.svg";
import {ReactComponent as PT} from "./svg/pt.svg";
import {ReactComponent as PW} from "./svg/pw.svg";
import {ReactComponent as PY} from "./svg/py.svg";
import {ReactComponent as QA} from "./svg/qa.svg";
import {ReactComponent as RE} from "./svg/re.svg";
import {ReactComponent as RO} from "./svg/ro.svg";
import {ReactComponent as RU} from "./svg/ru.svg";
import {ReactComponent as RW} from "./svg/rw.svg";
import {ReactComponent as SA} from "./svg/sa.svg";
import {ReactComponent as SB} from "./svg/sb.svg";
import {ReactComponent as SC} from "./svg/sc.svg";
import {ReactComponent as SD} from "./svg/sd.svg";
import {ReactComponent as SE} from "./svg/se.svg";
import {ReactComponent as SG} from "./svg/sg.svg";
import {ReactComponent as SH} from "./svg/sh.svg";
import {ReactComponent as SI} from "./svg/si.svg";
import {ReactComponent as SJ} from "./svg/sj.svg";
import {ReactComponent as SK} from "./svg/sk.svg";
import {ReactComponent as SL} from "./svg/sl.svg";
import {ReactComponent as SM} from "./svg/sm.svg";
import {ReactComponent as SN} from "./svg/sn.svg";
import {ReactComponent as SO} from "./svg/so.svg";
import {ReactComponent as SR} from "./svg/sr.svg";
import {ReactComponent as SS} from "./svg/ss.svg";
import {ReactComponent as ST} from "./svg/st.svg";
import {ReactComponent as SV} from "./svg/sv.svg";
import {ReactComponent as SX} from "./svg/sx.svg";
import {ReactComponent as SY} from "./svg/sy.svg";
import {ReactComponent as SZ} from "./svg/sz.svg";
import {ReactComponent as TA} from "./svg/ta.svg";
import {ReactComponent as TC} from "./svg/tc.svg";
import {ReactComponent as TD} from "./svg/td.svg";
import {ReactComponent as TF} from "./svg/tf.svg";
import {ReactComponent as TG} from "./svg/tg.svg";
import {ReactComponent as TH} from "./svg/th.svg";
import {ReactComponent as TJ} from "./svg/tj.svg";
import {ReactComponent as TK} from "./svg/tk.svg";
import {ReactComponent as TL} from "./svg/tl.svg";
import {ReactComponent as TM} from "./svg/tm.svg";
import {ReactComponent as TN} from "./svg/tn.svg";
import {ReactComponent as TO} from "./svg/to.svg";
import {ReactComponent as TR} from "./svg/tr.svg";
import {ReactComponent as TT} from "./svg/tt.svg";
import {ReactComponent as TV} from "./svg/tv.svg";
import {ReactComponent as TW} from "./svg/tw.svg";
import {ReactComponent as TZ} from "./svg/tz.svg";
import {ReactComponent as UA} from "./svg/ua.svg";
import {ReactComponent as UG} from "./svg/ug.svg";
import {ReactComponent as UM} from "./svg/um.svg";
import {ReactComponent as UN} from "./svg/un.svg";
import {ReactComponent as US} from "./svg/us.svg";
import {ReactComponent as UY} from "./svg/uy.svg";
import {ReactComponent as UZ} from "./svg/uz.svg";
import {ReactComponent as VA} from "./svg/va.svg";
import {ReactComponent as VC} from "./svg/vc.svg";
import {ReactComponent as VE} from "./svg/ve.svg";
import {ReactComponent as VG} from "./svg/vg.svg";
import {ReactComponent as VI} from "./svg/vi.svg";
import {ReactComponent as VN} from "./svg/vn.svg";
import {ReactComponent as VU} from "./svg/vu.svg";
import {ReactComponent as WF} from "./svg/wf.svg";
import {ReactComponent as WS} from "./svg/ws.svg";
import {ReactComponent as XK} from "./svg/xk.svg";
import {ReactComponent as YE} from "./svg/ye.svg";
import {ReactComponent as YT} from "./svg/yt.svg";
import {ReactComponent as ZA} from "./svg/za.svg";
import {ReactComponent as ZM} from "./svg/zm.svg";
import {ReactComponent as ZW} from "./svg/zw.svg";

export default class Flags extends React.Component{
    constructor(props) {
        super(props);
    };

    render() {
        switch(this.props.country) {
            case "AC" : return <AC />; break;
            case "AD" : return <AD />; break;
            case "AE" : return <AE />; break;
            case "AF" : return <AF />; break;
            case "AG" : return <AG />; break;
            case "AI" : return <AI />; break;
            case "AL" : return <AL />; break;
            case "AM" : return <AM />; break;
            case "AO" : return <AO />; break;
            case "AQ" : return <AQ />; break;
            case "AR" : return <AR />; break;
            case "AS" : return <AS />; break;
            case "AT" : return <AT />; break;
            case "AU" : return <AU />; break;
            case "AW" : return <AW />; break;
            case "AX" : return <AX />; break;
            case "AZ" : return <AZ />; break;
            case "BA" : return <BA />; break;
            case "BB" : return <BB />; break;
            case "BD" : return <BD />; break;
            case "BE" : return <BE />; break;
            case "BF" : return <BF />; break;
            case "BG" : return <BG />; break;
            case "BH" : return <BH />; break;
            case "BI" : return <BI />; break;
            case "BJ" : return <BJ />; break;
            case "BL" : return <BL />; break;
            case "BM" : return <BM />; break;
            case "BN" : return <BN />; break;
            case "BO" : return <BO />; break;
            case "BQ" : return <BQ />; break;
            case "BR" : return <BR />; break;
            case "BS" : return <BS />; break;
            case "BT" : return <BT />; break;
            case "BV" : return <BV />; break;
            case "BW" : return <BW />; break;
            case "BY" : return <BY />; break;
            case "BZ" : return <BZ />; break;
            case "CA" : return <CA />; break;
            case "CC" : return <CC />; break;
            case "CD" : return <CD />; break;
            case "CF" : return <CF />; break;
            case "CG" : return <CG />; break;
            case "CH" : return <CH />; break;
            case "CI" : return <CI />; break;
            case "CK" : return <CK />; break;
            case "CL" : return <CL />; break;
            case "CM" : return <CM />; break;
            case "CN" : return <CN />; break;
            case "CO" : return <CO />; break;
            case "CP" : return <CP />; break;
            case "CR" : return <CR />; break;
            case "CU" : return <CU />; break;
            case "CV" : return <CV />; break;
            case "CW" : return <CW />; break;
            case "CX" : return <CX />; break;
            case "CY" : return <CY />; break;
            case "CZ" : return <CZ />; break;
            case "DE" : return <DE />; break;
            case "DG" : return <DG />; break;
            case "DJ" : return <DJ />; break;
            case "DK" : return <DK />; break;
            case "DM" : return <DM />; break;
            case "DO" : return <DO />; break;
            case "DZ" : return <DZ />; break;
            case "EA" : return <EA />; break;
            case "EC" : return <EC />; break;
            case "EE" : return <EE />; break;
            case "EG" : return <EG />; break;
            case "EH" : return <EH />; break;
            case "EN" : return <EN />; break;
            case "ER" : return <ER />; break;
            case "ES" : return <ES />; break;
            case "ET" : return <ET />; break;
            case "EU" : return <EU />; break;
            case "FI" : return <FI />; break;
            case "FJ" : return <FJ />; break;
            case "FK" : return <FK />; break;
            case "FM" : return <FM />; break;
            case "FO" : return <FO />; break;
            case "FR" : return <FR />; break;
            case "GA" : return <GA />; break;
            case "GB" : return <GB />; break;
            case "GD" : return <GD />; break;
            case "GE" : return <GE />; break;
            case "GF" : return <GF />; break;
            case "GG" : return <GG />; break;
            case "GH" : return <GH />; break;
            case "GI" : return <GI />; break;
            case "GL" : return <GL />; break;
            case "GM" : return <GM />; break;
            case "GN" : return <GN />; break;
            case "GP" : return <GP />; break;
            case "GQ" : return <GQ />; break;
            case "GR" : return <GR />; break;
            case "GS" : return <GS />; break;
            case "GT" : return <GT />; break;
            case "GU" : return <GU />; break;
            case "GW" : return <GW />; break;
            case "GY" : return <GY />; break;
            case "HK" : return <HK />; break;
            case "HM" : return <HM />; break;
            case "HN" : return <HN />; break;
            case "HR" : return <HR />; break;
            case "HT" : return <HT />; break;
            case "HU" : return <HU />; break;
            case "IC" : return <IC />; break;
            case "ID" : return <ID />; break;
            case "IE" : return <IE />; break;
            case "IL" : return <IL />; break;
            case "IM" : return <IM />; break;
            case "IN" : return <IN />; break;
            case "IO" : return <IO />; break;
            case "IQ" : return <IQ />; break;
            case "IR" : return <IR />; break;
            case "IS" : return <IS />; break;
            case "IT" : return <IT />; break;
            case "JE" : return <JE />; break;
            case "JM" : return <JM />; break;
            case "JO" : return <JO />; break;
            case "JP" : return <JP />; break;
            case "KE" : return <KE />; break;
            case "KG" : return <KG />; break;
            case "KH" : return <KH />; break;
            case "KI" : return <KI />; break;
            case "KM" : return <KM />; break;
            case "KN" : return <KN />; break;
            case "KP" : return <KP />; break;
            case "KR" : return <KR />; break;
            case "KW" : return <KW />; break;
            case "KY" : return <KY />; break;
            case "KZ" : return <KZ />; break;
            case "LA" : return <LA />; break;
            case "LB" : return <LB />; break;
            case "LC" : return <LC />; break;
            case "LI" : return <LI />; break;
            case "LK" : return <LK />; break;
            case "LR" : return <LR />; break;
            case "LS" : return <LS />; break;
            case "LT" : return <LT />; break;
            case "LU" : return <LU />; break;
            case "LV" : return <LV />; break;
            case "LY" : return <LY />; break;
            case "MA" : return <MA />; break;
            case "MC" : return <MC />; break;
            case "MD" : return <MD />; break;
            case "ME" : return <ME />; break;
            case "MF" : return <MF />; break;
            case "MG" : return <MG />; break;
            case "MH" : return <MH />; break;
            case "MK" : return <MK />; break;
            case "ML" : return <ML />; break;
            case "MM" : return <MM />; break;
            case "MN" : return <MN />; break;
            case "MO" : return <MO />; break;
            case "MP" : return <MP />; break;
            case "MQ" : return <MQ />; break;
            case "MR" : return <MR />; break;
            case "MS" : return <MS />; break;
            case "MT" : return <MT />; break;
            case "MU" : return <MU />; break;
            case "MV" : return <MV />; break;
            case "MW" : return <MW />; break;
            case "MX" : return <MX />; break;
            case "MY" : return <MY />; break;
            case "MZ" : return <MZ />; break;
            case "NA" : return <NA />; break;
            case "NC" : return <NC />; break;
            case "NE" : return <NE />; break;
            case "NF" : return <NF />; break;
            case "NG" : return <NG />; break;
            case "NI" : return <NI />; break;
            case "NL" : return <NL />; break;
            case "NO" : return <NO />; break;
            case "NP" : return <NP />; break;
            case "NR" : return <NR />; break;
            case "NU" : return <NU />; break;
            case "NZ" : return <NZ />; break;
            case "OM" : return <OM />; break;
            case "PA" : return <PA />; break;
            case "PE" : return <PE />; break;
            case "PF" : return <PF />; break;
            case "PG" : return <PG />; break;
            case "PH" : return <PH />; break;
            case "PK" : return <PK />; break;
            case "PL" : return <PL />; break;
            case "PM" : return <PM />; break;
            case "PN" : return <PN />; break;
            case "PR" : return <PR />; break;
            case "PS" : return <PS />; break;
            case "PT" : return <PT />; break;
            case "PW" : return <PW />; break;
            case "PY" : return <PY />; break;
            case "QA" : return <QA />; break;
            case "RE" : return <RE />; break;
            case "RO" : return <RO />; break;
            case "RU" : return <RU />; break;
            case "RW" : return <RW />; break;
            case "SA" : return <SA />; break;
            case "SB" : return <SB />; break;
            case "SC" : return <SC />; break;
            case "SD" : return <SD />; break;
            case "SE" : return <SE />; break;
            case "SG" : return <SG />; break;
            case "SH" : return <SH />; break;
            case "SI" : return <SI />; break;
            case "SJ" : return <SJ />; break;
            case "SK" : return <SK />; break;
            case "SL" : return <SL />; break;
            case "SM" : return <SM />; break;
            case "SN" : return <SN />; break;
            case "SO" : return <SO />; break;
            case "SR" : return <SR />; break;
            case "SS" : return <SS />; break;
            case "ST" : return <ST />; break;
            case "SV" : return <SV />; break;
            case "SX" : return <SX />; break;
            case "SY" : return <SY />; break;
            case "SZ" : return <SZ />; break;
            case "TA" : return <TA />; break;
            case "TC" : return <TC />; break;
            case "TD" : return <TD />; break;
            case "TF" : return <TF />; break;
            case "TG" : return <TG />; break;
            case "TH" : return <TH />; break;
            case "TJ" : return <TJ />; break;
            case "TK" : return <TK />; break;
            case "TL" : return <TL />; break;
            case "TM" : return <TM />; break;
            case "TN" : return <TN />; break;
            case "TO" : return <TO />; break;
            case "TR" : return <TR />; break;
            case "TT" : return <TT />; break;
            case "TV" : return <TV />; break;
            case "TW" : return <TW />; break;
            case "TZ" : return <TZ />; break;
            case "UA" : return <UA />; break;
            case "UG" : return <UG />; break;
            case "UM" : return <UM />; break;
            case "UN" : return <UN />; break;
            case "US" : return <US />; break;
            case "UY" : return <UY />; break;
            case "UZ" : return <UZ />; break;
            case "VA" : return <VA />; break;
            case "VC" : return <VC />; break;
            case "VE" : return <VE />; break;
            case "VG" : return <VG />; break;
            case "VI" : return <VI />; break;
            case "VN" : return <VN />; break;
            case "VU" : return <VU />; break;
            case "WF" : return <WF />; break;
            case "WS" : return <WS />; break;
            case "XK" : return <XK />; break;
            case "YE" : return <YE />; break;
            case "YT" : return <YT />; break;
            case "ZA" : return <ZA />; break;
            case "ZM" : return <ZM />; break;
            case "ZW" : return <ZW />; break;
            default : return ""; break;
        }
    }
};